### ISSUE TITLE
Errors installing packages 

### ISSUE THREAD

**Issue by leftcoastbeard** [OneGet/oneget#170]
I'm having a similar (and possibly related to issue #169 ) issue installing packages.
I am attempting to install proget on a Windows 10 box as described below:
```
PS C:\WINDOWS\system32> install-package proget
install-package : Unable to resolve package dependency -- package 'chocolatey:vcredist2008' not found.
At line:1 char:1
+ install-package proget
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (chocolatey:SqlS...tey.org/api/v2/:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnableToResolveDependency_dependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdle
   ts.InstallPackage

PS C:\WINDOWS\system32> install-package proget -ProviderName chocolatey -verbose
VERBOSE: Exception : DefaultDomain//InvalidOperationException/An error occurred while processing this request.
   at NuGet.DataServiceQueryWrapper`1.Execute[TResult](Func`1 action)
   at NuGet.DataServiceQueryWrapper`1.<GetAll>d__7.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PackageManagement.ChocolateyPrototype.ChocolateyRequest.GetPackageById(PackageSource source, String
name, String requiredVersion, String minimumVersion, String maximumVersion, Boolean allowUnlisted)
VERBOSE: Performing the operation "Install Package" on target "Package 'proget' version '4.0.6' from 'chocolatey'".
```

However, if I search for the package first and pipe it into the install, it sort of complains (but doesn't actually install):
```
PS C:\WINDOWS\system32> find-package proget -verbose -ProviderName chocolatey | Install-Package -verbose
VERBOSE: Performing the operation "Install Package" on target "Package 'proget' version '4.0.6' from 'chocolatey'".
VERBOSE: NuGet: GET http://chocolatey.org/api/v2/Packages(Id='vcredist2008',Version='9.0.30729.6161')
VERBOSE: NuGet: GET http://chocolatey.org/api/v2/package/vcredist2008/9.0.30729.6161
WARNING: NuGet: System.IO.InvalidDataException: Unable to read package from path 'vcredist2008.9.0.30729.6161.nupkg'.
---> System.IO.FileFormatException: File contains corrupted data.
WARNING: NuGet:    at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
WARNING: NuGet:    at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
WARNING: NuGet:    at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access,
Boolean streaming, Boolean ownStream)
WARNING: NuGet:    at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access,
Boolean streaming)
WARNING: NuGet:    at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean
streaming)
WARNING: NuGet:    at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess,
Boolean streaming)
WARNING: NuGet:    at NuGet.OptimizedZipPackage.EnsureManifest()
WARNING: NuGet:    at NuGet.LocalPackageRepository.OpenPackage(String path)
WARNING: NuGet:    --- End of inner exception stack trace ---
WARNING: NuGet:    at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
WARNING: NuGet:    at NuGet.LocalPackageRepository.<>c__DisplayClass13.<FindPackage>b__f(String path)
WARNING: NuGet:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
WARNING: NuGet:    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
WARNING: NuGet:    at NuGet.LocalPackageRepository.FindPackage(Func`2 openPackage, String packageId, SemanticVersion
version)
WARNING: NuGet:    at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId,
SemanticVersion version, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean
allowUnlisted)
WARNING: NuGet:    at NuGet.DataServicePackage.EnsurePackage(IPackageCacheRepository cacheRepository)
WARNING: NuGet:    at NuGet.DataServicePackage.get_FrameworkAssemblies()
WARNING: NuGet:    at NuGet.PackageExtensions.HasProjectContent(IPackage package)
WARNING: NuGet:    at NuGet.PackageWalker.GetPackageTarget(IPackage package)
WARNING: NuGet:    at NuGet.PackageWalker.GetPackageInfo(IPackage package)
WARNING: NuGet:    at NuGet.PackageWalker.ProcessPackageTarget(IPackage package)
WARNING: NuGet:    at NuGet.PackageWalker.Walk(IPackage package)
WARNING: NuGet:    at NuGet.InstallWalker.ResolveOperations(IPackage package)
WARNING: NuGet:    at NuGet.PackageManager.Execute(IPackage package, IPackageOperationResolver resolver)
WARNING: NuGet:    at NuGet.PackageManager.InstallPackage(IPackage package, Boolean ignoreDependencies, Boolean
allowPrereleaseVersions)
WARNING: NuGet:    at NuGet.Commands.InstallCommand.InstallPackage(IFileSystem fileSystem, String packageId,
SemanticVersion version)
WARNING: NuGet:    at NuGet.Program.Main(String[] args)
VERBOSE: Skipped Package 'vcredist2008 v9.0.30729.6161' already installed
VERBOSE: NuGet: GET http://chocolatey.org/api/v2/Packages(Id='SqlServerExpress',Version='10.0.0.20130503')
VERBOSE: NuGet: Attempting to resolve dependency 'vcredist2008'.
WARNING: NuGet:    at NuGet.LocalPackageRepository.<GetPackages>d__15.MoveNext()
WARNING: NuGet:    at NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
WARNING: NuGet:    at NuGet.LocalPackageRepository.FindPackagesById(Func`2 openPackage, String packageId)
WARNING: NuGet:    at NuGet.PackageRepositoryExtensions.FindPackagesById(IPackageRepository repository, String
packageId)
WARNING: NuGet:    at NuGet.PriorityPackageRepository.FindPackagesById(String packageId)
WARNING: NuGet:    at NuGet.PackageRepositoryExtensions.ResolveDependencyCore(IPackageRepository repository,
PackageDependency dependency, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean
preferListedPackages, DependencyVersion dependencyVersion)
WARNING: NuGet:    at NuGet.InstallWalker.ResolveDependency(PackageDependency dependency)
VERBOSE: Skipped Package 'SqlServerExpress v10.0.0.20130503' already installed
VERBOSE: NuGet: GET http://chocolatey.org/api/v2/Packages(Id='proget',Version='4.0.6')
VERBOSE: NuGet: Attempting to resolve dependency 'SqlServerExpress (≥ 10.0.0.20130503)'.
VERBOSE: NuGet: GET http://chocolatey.org/api/v2/FindPackagesById()?id='SqlServerExpress'
VERBOSE: NuGet: GET http://chocolatey.org/api/v2/package/SqlServerExpress/10.0.0.20130503
WARNING: NuGet: System.IO.InvalidDataException: Unable to read package from path
'SqlServerExpress.10.0.0.20130503.nupkg'. ---> System.IO.FileFormatException: File contains corrupted data.
VERBOSE: Skipped Package 'proget v4.0.6' already installed
```
It says skipped Package at the end and so I then check for install:
```
PS C:\WINDOWS\system32> get-package proget -verbose
VERBOSE: Skipping package provider provider 'NuGet'-- missing required option 'Destination'
get-package : No package found for  'proget'.
At line:1 char:1
+ get-package proget -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...lets.GetPackage:GetPackage) [Get-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackage
```
I have also had similar issues installing other packages on other machines after the WMF5.0 RTM update (eg: installing the package "adobeshockwaveplayer" on Windows 8.1; I have the command output saved on another machine at the moment)
 
Would this be an issue with OneGet or Chocolatey or even the package itself? Any thoughts or suggestions?

**Comment by leftcoastbeard** [comment]
This seems to have resolved itself, most likely an issue with Chocolatey.org itself. They've been up and down several times over the last few days. Sorry to bother.
