### ISSUE TITLE
NuGet V3 exception for downloading packages from VSTS

### ISSUE THREAD

**Issue by jianyunt** [OneGet/oneget#341]
PS E:\> install-package -Name "Microsoft.Kusto.Tools" -Source "https://msazure.pkgs.visualstudio.com/_packaging/MSNugetMirror/nuget/v3/index.json" -debug -Credential (Get-Credential)

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
DEBUG: 00:00:00.0000003 Calling 'NuGet'::'ResolvePackageSources'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
DEBUG: 00:00:00.0000318 There are '3' registered sources in 'NuGet' provider.
DEBUG: 00:00:00.0000531 Yielding the package source: '«0»'. «NuGet» «Microsoft.PackageManagement.NuGetProvider.PackageSource»
DEBUG: 00:00:00.0000688 Yielding package source for temp at location https://msazure.pkgs.visualstudio.com/_packaging/MSNugetMirror/nuget/v3/index.json
DEBUG: 00:00:00.0000823 Returning the call 'NuGet'::'ResolvePackageSources'.
DEBUG: 00:00:01.4645318 Calling 'NuGet'::'ResolvePackageSources'.
DEBUG: 00:00:01.4645681 There are '3' registered sources in 'NuGet' provider.
DEBUG: 00:00:01.4645928 Yielding the package source: '«0»'. «NuGet» «Microsoft.PackageManagement.NuGetProvider.PackageSource»
DEBUG: 00:00:01.4646111 Yielding package source for temp at location https://msazure.pkgs.visualstudio.com/_packaging/MSNugetMirror/nuget/v3/index.json
DEBUG: 00:00:01.4646264 Returning the call 'NuGet'::'ResolvePackageSources'.
DEBUG: 00:00:01.4647707 Calling SearchForPackages. Name='Microsoft.Kusto.Tools'
VERBOSE: Using the provider 'NuGet' for searching packages.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
DEBUG: 00:00:01.4657454 PackageProvider::FindPackage with name Microsoft.Kusto.Tools
DEBUG: 00:00:01.4662445 Calling SearchForPackages After Select 1
DEBUG: 00:00:01.4677627 Calling 'NuGet'::'FindPackage' - name='Microsoft.Kusto.Tools', requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:01.4677892 Iterating 'Microsoft.Kusto.Tools'.
DEBUG: 00:00:01.4679616 There are '3' registered sources in 'NuGet' provider.
DEBUG: 00:00:01.4679905 Calling 'NuGetRequest'::'GetPackageById', 'Microsoft.Kusto.Tools'.
DEBUG: 00:00:01.4680371 Calling 'NuGetPackageRepository'::'FindPackagesById', 'Microsoft.Kusto.Tools'.
DEBUG: 00:00:01.4680623 Calling 'NuGetPackageFeed3'::'Find', 'Microsoft.Kusto.Tools'.
DEBUG: 00:00:01.4680782 Calling 'NuGetPackageFeed3'::'FindImpl', 'Microsoft.Kusto.Tools'.
DEBUG: 00:00:01.4680944 Returning the call 'NuGetPackageFeed3'::'FindImpl'.
DEBUG: 00:00:01.4681104 Returning the call 'NuGetPackageFeed3'::'Find'.
DEBUG: 00:00:01.4681542 Calling 'NuGetPackageFeed3'::'Find',
'https://msazure.pkgs.visualstudio.com/_packaging/2af09012-5751-4b91-ac82-0e831b12339e/nuget/v3/registrations2/microsoft.kusto.tools/index.json'.
DEBUG: 00:00:01.4681732 Downloading
'https://msazure.pkgs.visualstudio.com/_packaging/2af09012-5751-4b91-ac82-0e831b12339e/nuget/v3/registrations2/microsoft.kusto.tools/index.json'.
DEBUG: 00:00:01.8046695 Completed downloading
'https://msazure.pkgs.visualstudio.com/_packaging/2af09012-5751-4b91-ac82-0e831b12339e/nuget/v3/registrations2/microsoft.kusto.tools/index.json'.
DEBUG: 00:00:01.8213546 Calling 'NuGetFilesFeed3'::'GetVersionInfo'.
DEBUG: 00:00:01.8214276 Downloading
'https://msazure.pkgs.visualstudio.com/_packaging/2af09012-5751-4b91-ac82-0e831b12339e/nuget/v3/flat2/microsoft.kusto.tools/index.json'.
DEBUG: 00:00:01.9214906 Completed downloading
'https://msazure.pkgs.visualstudio.com/_packaging/2af09012-5751-4b91-ac82-0e831b12339e/nuget/v3/flat2/microsoft.kusto.tools/index.json'.
DEBUG: 00:00:01.9230927 Returning the call 'NuGetFilesFeed3'::'GetVersionInfo'.
DEBUG: 00:00:01.9231480 Calling 'NuGetPackageFeed3'::'Find', 'Microsoft.Kusto.Tools'.
DEBUG: 00:00:01.9231807 Calling 'NuGetPackageFeed3'::'FindImpl', 'Microsoft.Kusto.Tools'.
DEBUG: 00:00:01.9232204 Returning the call 'NuGetPackageFeed3'::'FindImpl'.
DEBUG: 00:00:01.9232543 Returning the call 'NuGetPackageFeed3'::'Find'.
DEBUG: 00:00:01.9233286 Calling 'NuGetPackageFeed3'::'Find',
'https://msazure.pkgs.visualstudio.com/_packaging/2af09012-5751-4b91-ac82-0e831b12339e/nuget/v3/registrations2/microsoft.kusto.tools/1.0.4.json'.
DEBUG: 00:00:01.9233694 Downloading
'https://msazure.pkgs.visualstudio.com/_packaging/2af09012-5751-4b91-ac82-0e831b12339e/nuget/v3/registrations2/microsoft.kusto.tools/1.0.4.json'.
DEBUG: 00:00:02.0684748 Completed downloading
'https://msazure.pkgs.visualstudio.com/_packaging/2af09012-5751-4b91-ac82-0e831b12339e/nuget/v3/registrations2/microsoft.kusto.tools/1.0.4.json'.
DEBUG: 00:00:02.0843733 Downloading
'https://msazure.pkgs.visualstudio.com/_apis/packaging/2af09012-5751-4b91-ac82-0e831b12339e/nuget/commitLog/e664b056c88a4e0292078091fbeab152'.
DEBUG: 00:00:02.1965752 Completed downloading
'https://msazure.pkgs.visualstudio.com/_apis/packaging/2af09012-5751-4b91-ac82-0e831b12339e/nuget/commitLog/e664b056c88a4e0292078091fbeab152'.
DEBUG: 00:00:02.2015906 System.AggregateException: One or more errors occurred. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException:
'System.Dynamic.ExpandoObject' does not contain a definition for 'version'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.GetPackageFromCatalogUrl(String catalogUrl, RequestWrapper request, HashSet`1
packageSemanticVersions, NuGetSearchContext context)
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.<>c__DisplayClass2_1.<Find>b__0()
   at Microsoft.PackageManagement.NuGetProvider.ConcurrentInMemoryCache.GetOrAdd[T](String key, Func`1 constructor)
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.Find(String registrationUrl, NuGetSearchContext context, RequestWrapper request, Boolean
finalAttempt)
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.<GetPackagesForBaseUrl>d__6.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.Find(String registrationUrl, NuGetSearchContext context, RequestWrapper request, Boolean
finalAttempt)
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.<GetPackagesForBaseUrl>d__6.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at Microsoft.PackageManagement.NuGetProvider.NuGetRequest.YieldPackages(IEnumerable`1 packageReferences, String searchKey)
   at Microsoft.PackageManagement.NuGetProvider.NuGetProvider.FindPackage(String name, String requiredVersion, String minimumVersion, String
maximumVersion, Int32 id, NuGetRequest request)
---> (Inner Exception #0) Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Dynamic.ExpandoObject' does not contain a definition for
'version'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.GetPackageFromCatalogUrl(String catalogUrl, RequestWrapper request, HashSet`1
packageSemanticVersions, NuGetSearchContext context)
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.<>c__DisplayClass2_1.<Find>b__0()
   at Microsoft.PackageManagement.NuGetProvider.ConcurrentInMemoryCache.GetOrAdd[T](String key, Func`1 constructor)
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.Find(String registrationUrl, NuGetSearchContext context, RequestWrapper request, Boolean
finalAttempt)
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.<GetPackagesForBaseUrl>d__6.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.Find(String registrationUrl, NuGetSearchContext context, RequestWrapper request, Boolean
finalAttempt)
   at Microsoft.PackageManagement.NuGetProvider.NuGetPackageFeed3.<GetPackagesForBaseUrl>d__6.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---
DEBUG: 00:00:02.6287882 unmatched package name='Microsoft.Kusto.Tools'

Confirm
No match was found for the specified search criteria and package name 'Microsoft.Kusto.Tools'. Try Get-PackageSource to see all available registered
package sources.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
install-package : No match was found for the specified search criteria and package name 'Microsoft.Kusto.Tools'. Try Get-PackageSource to see all available
registered package sources.
At line:1 char:1
+ install-package -Name "Microsoft.Kusto.Tools" -Source temp -debug -Cr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by jianyunt** [comment]
@ alerickson to repro the problem, you need to have a personal access token as logon password.  I guess 
- you need to have access permission to the source location
- create personal access token
    You can go to https://msazure.visualstudio.com/, click on your picture, select Security, and add will generate a token

- install-package -Name "Microsoft.Kusto.Tools" -Source "https://msazure.pkgs.visualstudio.com/_packaging/MSNugetMirror/nuget/v3/index.json" -debug -Credential (Get-Credential)
 user name is the name you use to logon to the https://msazure.visualstudio.com/, password is the token.
