### ISSUE TITLE
Install-Module fails to download package from VSTS package management feed in PS Core

### ISSUE THREAD

**Issue by bmanikm** [OneGet/oneget#342]
_From @shrimma on March 7, 2018 16:48_

## Expected Behavior
Install-Module should download and install a package from VSTS nuget feed successfully.

## Current Behavior
When attempting to Install-Module in PS Core 6.0.1 the following error occurs during download:
```
VERBOSE: Object reference not set to an instance of an object.
DEBUG: 00:00:18.0195353    at System.Net.Http.WinHttpAuthHelper.SaveServerCredentialsToCache(Uri uri, UInt32 authScheme, ICredentials serverCredentials)
   at System.Net.Http.WinHttpAuthHelper.CheckResponseForAuthentication(WinHttpRequestState state, UInt32& proxyAuthScheme, UInt32& serverAuthScheme)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__15.MoveNext()
```

The command works as expected in PowerShell Windows v5.

## Steps to Reproduce (for bugs)
1. Create and publish a module to VSTS package management feed
2. Register the repository
Register-PSRepository -Name "MyRepository" -SourceLocation "" -PublishLocation "" -Credential $cred -PackageManagementProvider Nuget -InstallationPolicy Trusted
3. Install-Module -Name "MyModule" -Repository "MyRepository" -Credential $cred

## Context
I am able to install a module from VSTS package management as expected in PowerShell Windows v5. But fails in Core 6.0.1.

## Your Environment
```PowerShell

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1
OS                             Microsoft Windows 10.0.16299
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> Get-Module
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty...}
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-Auth...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.1.7.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvide...
Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}
Script     1.2        PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKe...
> Get-Module -ListAvailable PowerShellGet,PackageManagement

    Directory: C:\program files\powershell\6.0.1\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     1.6.0      PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}

> Get-PackageProvider
Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains...
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpd...

> Get-PackageProvider -ListAvailable
Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains...
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpd...
```

_Copied from original issue: PowerShell/PowerShellGet#237_

**Comment by bmanikm** [comment]
_From @shrimma on March 13, 2018 9:38_

Note this command works from Ubuntu 16.04. So seems the issue is limited to Windows 10.
